### ISSUE TITLE
Conversion stopped midway

### ISSUE THREAD

**Issue by cosmeltics** [gusborg88/fnf-porter#47]
### What is the preset selected?

Full mod

### What platform?

Windows

### What are the contents of the latest .log file? (If you don't know what the last log file was, open the ".defaults" file, where you will find the name of the log file in the third line.)

19:44:18: [main.py:60] [INFO] Converting started...
19:44:18: [main.py:61] [INFO] {'charts': True, 'songs': {'inst': True, 'voices': True, 'split': True, 'music': True, 'sounds': True}, 'characters': {'icons': True, 'json': True, 'assets': True}, 'weeks': {'props': True, 'levels': True, 'titles': True}, 'stages': True, 'modpack_meta': True, 'images': True}
19:44:18: [main.py:66] [INFO] Converting fromC:/Users/fabio/Desktop/PsychEngine/mods/VSWHITTY to C:/Users/fabio/Desktop/Friday Night Funkin'/mods
19:44:18: [main.py:69] [INFO] Converting pack.json
19:44:18: [log.py:59] [ERROR] Uncaught exception
Traceback (most recent call last):
  File "src\window.py", line 476, in convertCallback
  File "main.py", line 76, in convert
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid control character at: line 3 column 292 (char 317)
19:44:22: [window.py:490]

### What are the contents of your mod folder?

It's the V.S. Whitty modpack, the definitve one, just altered a bit to only have the bonus week.

### Issue Checklist

- [ ] I have properly named the issue
- [ ] I looked in issues/discussions, if my question was previously anwsered

**Comment by BombasticTom** [comment]
Can you show your mod's `pack.json`?

**Comment by cosmeltics** [comment]
{
	"name": "V.S. Whitty",
	"description": "While strolling with your Girlfriend though an alleyway, you notice an ominous glow coming from around the corner. Out steps Whitmore, a hot-headed rock star who happens to have some beef with your Girlfriend's parents. Think you've got what it takes to get him outta there?
This mod adds a bonus week for you to fight against Whitty. All credits to the devs of VS Whitty.",
	"restart":false,
	"runsGlobally": true,
	"color": [128,128,128]
}

**Comment by BombasticTom** [comment]
try copy-pasting this

```json
{
	"name": "V.S. Whitty",
	"description": "While strolling with your Girlfriend though an alleyway, you notice an ominous glow coming from around the corner. Out steps Whitmore, a hot-headed rock star who happens to have some beef with your Girlfriend's parents. Think you've got what it takes to get him outta there? This mod adds a bonus week for you to fight against Whitty. All credits to the devs of VS Whitty.",
	"restart":false,
	"runsGlobally": true,
	"color": [128,128,128]
}
```

**Comment by BombasticTom** [comment]
The JSON you provided had an invalid line break, which made the Converter stop it's operations.

```json
{
"name": "V.S. Whitty",
"description": "While strolling with your Girlfriend though an alleyway, you notice an ominous glow coming from around the corner. Out steps Whitmore, a hot-headed rock star who happens to have some beef with your Girlfriend's parents. Think you've got what it takes to get him outta there?
This mod adds a bonus week for you to fight against Whitty. All credits to the devs of VS Whitty.",
"restart":false,
"runsGlobally": true,
"color": [128,128,128]
}
```

**Comment by cosmeltics** [comment]
Thanks! Atleast I can convert the sprites & although the offsets are off & the vocals don't play, i'll fix that myself but when I hover on the week on story menu, my game crashes.
![Screenshot 2024-05-28 092324](https://github.com/gusborg88/fnf-porter/assets/116808086/80f59ca0-374b-4e6d-9aaf-1f72802bdae7)
